include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for AT WebServer
LUCI_DEPENDS:=+at-webserver +luci-app-modem
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-at-webserver
PKG_VERSION:=1.0
PKG_RELEASE:=35

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
